api:
  url: http://localhost:8000
env:
  sources:
    # - kind: deviceManager
    #   module: dodal.beamlines.i19_2
    - kind: planFunctions
      module: dodal.plan_stubs
stomp:
  enabled: false
logging:
  level: "INFO"
    # graylog:
    #   enabled: True
